---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git:
            repoURL: 'https://github.com/marsu-p/argocd_testbench.git'
            revision: HEAD
            files:
              - path: 'values/version-{{ index .metadata.labels "cluster_env" }}.yaml'
  template:
    metadata:
      name: '{{ .name }}-kyverno'
    spec:
      project: default
      sources:
        - chart: kyverno
          repoURL: 'https://kyverno.github.io/kyverno'
          targetRevision: '{{ .values.revision }}'
          helm:
            releaseName: kyverno
            parameters:
              - name: "global.additionalLabels.argocd-enabled"
                value: '{{ . }}'
            valueFiles:
              - $kyverno/values/values-all.yaml
              - $kyverno/values/values-{{ .name }}.yaml
              - $kyverno/values/values-{{ .name }}-version.yaml
        - repoURL: 'https://github.com/marsu-p/argocd_testbench.git'
          targetRevision: main
          ref: kyverno
      destination:
        name: '{{ .name }}'
        namespace: kyverno
      syncPolicy:
        syncOptions:
          - PrunePropagationPolicy=background
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
          - FailOnSharedResource=true
          - CreateNamespace=false